root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp\\server.exe"
  cmd = "go build -o tmp/server.exe ./cmd/server"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "node_modules"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  kill_delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
